CREATE OR REPLACE TABLE RESTAURANT_ANALYTICS.RAW_DATA.INVOICES_EXTRACTED AS
WITH temp AS (
  SELECT 
    relative_path as file_name,
    size as file_size,
    last_modified,
    file_url,
    INVOICES!PREDICT(
      GET_PRESIGNED_URL(@RESTAURANT_ANALYTICS.RAW_DATA.INVOICES, relative_path),
      1
    ) as predicted_data
  FROM DIRECTORY(@RESTAURANT_ANALYTICS.RAW_DATA.INVOICES)
)
SELECT 
  file_name,
  predicted_data:invoice_number::VARCHAR as invoice_number,
  predicted_data:invoice_date::DATE as invoice_date,
  predicted_data:total_amount::NUMBER(10,2) as total_amount,
  predicted_data:vendor_name::VARCHAR as vendor_name,
  -- add other fields as needed
  last_modified
FROM temp;

RESTAURANT_ANALYTICS.RAW_DATA
GRANT CREATE SNOWFLAKE.ML.DOCUMENT_INTELLIGENCE ON SCHEMA RESTAURANT_ANALYTICS.RAW_DATA TO ROLE ACCOUNTADMIN;
GRANT CREATE MODEL ON SCHEMA RESTAURANT_ANALYTICS.RAW_DATA TO ROLE ACCOUNTADMIN;

GRANT CREATE STREAM, CREATE TABLE, CREATE TASK, CREATE VIEW ON SCHEMA RESTAURANT_ANALYTICS.RAW_DATA TO ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE ACCOUNTADMIN;


CREATE or replace TABLE  RESTAURANT_ANALYTICS.RAW_DATA.INVOICES_PDF (
            FILE_NAME VARCHAR(500),
            UPLOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
            RAW_DATA VARIANT
        );



select * from RESTAURANT_ANALYTICS.RAW_DATA.INVOICES_PDF;

CREATE or replace TABLE  RESTAURANT_ANALYTICS.RAW_DATA.INVOICES_RAW (
            INVOICE_ID INT AUTOINCREMENT,
            FILE_NAME VARCHAR(500),
            UPLOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
            PDF_TEXT TEXT,
            RAW_DATA VARIANT
        );


CREATE or replace TABLE  RESTAURANT_ANALYTICS.RAW_DATA.INVOICES_STRUCTURED (
            INVOICE_ID INT,
            INVOICE_NUMBER VARCHAR(50),
            VENDOR_NAME VARCHAR(200),
            INVOICE_DATE DATE,
            DUE_DATE DATE,
            BILL_TO VARCHAR(500),
            SHIP_TO VARCHAR(500),
            TOTAL_AMOUNT DECIMAL(10,2),
            LINE_ITEMS VARIANT,
            PROCESSED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
        )

select * from RESTAURANT_ANALYTICS.RAW_DATA.INVOICES_RAW ;

delete from  RESTAURANT_ANALYTICS.RAW_DATA.INVOICES_STRUCTURED;

